[project]
name = "data_store"
version = "0.1.0"
description = ""
authors = [
    { name = "Timothy Storm", email = "timothystorm@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "alembic (>=1.17.2,<2.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "psycopg2-binary (>=2.9.11,<3.0.0)",
    "pydantic (>=2.12.5,<3.0.0)",
    "pydantic-settings (>=2.12.0,<3.0.0)"
]

[virtualenvs]
in-project = true

[tool.poetry]
packages = [{ include = "data_store", from = "src" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
mypy_path = ["src"]
exclude = [
    "^alembic/",
    ".*/conftest\\.py$"
]
ignore_missing_imports = true
explicit_package_bases = true

[tool.ruff]
exclude = ["alembic"]
